name: Kokodayo Web Portal
title: Kokodayo Web Portal
email: smith.zhou@mail.utoronto.ca
description: >- 
  Kokodayo © 4024: All rights reserved
url: https://www.kokodayo.us 

theme: minima
minima:
  skin: dark
author: Kokodayo
plugins:
  - jekyll-feed

exclude:
  - anti-inspect-element.js
