name: Kokodayo Web Portal
title: Kokodayo Web Portal
email: smith.zhou@mail.utoronto.ca
description: Kokodayo Web Portal © 2024 by Kokodayo-CN is licensed under CC BY-NC-ND 4.0 
url: https://www.kokodayo.us 

theme: minima
minima:
  skin: dark
author: Kokodayo
plugins:
  - jekyll-feed
exclude: ["_posts"]
