name: Kokodayo Web Portal
title: Kokodayo Web Portal
email: smith.zhou@mail.utoronto.ca
description: >-  
  Kokodayo © 4024: 保留所有权利
url: https://www.kokodayo.us 

theme: minima
minima:
  skin: dark
author: Kokodayo
plugins:
  - jekyll-feed
exclude: ["_posts"]
