name: Portail Web de Kokodayo
title: Portail Web de Kokodayo
email: smith.zhou@mail.utoronto.ca
description: >-  
  Kokodayo © 4024: Tous droits réservés
url: https://www.kokodayo.us 

theme: minima
minima:
  skin: dark
author: Kokodayo
plugins:
  - jekyll-feed
exclude: ["_posts"]
